services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: synclecta_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/app/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - synclecta
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: synclecta_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - synclecta
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: synclecta_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: synclecta
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: synclecta
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - synclecta

  redis:
    image: redis:7-alpine
    container_name: synclecta_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - synclecta

  queue:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: synclecta_queue
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    command: php artisan queue:work --sleep=3 --tries=3 --max-time=3600
    networks:
      - synclecta
    depends_on:
      - app
      - redis

  horizon:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: synclecta_horizon
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    command: php artisan horizon
    networks:
      - synclecta
    depends_on:
      - app
      - redis

networks:
  synclecta:
    driver: bridge

volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local 